# coding=utf-8

'''
This file has been generated by conjure-python version 0.0.0
https://github.com/palantir/conjure-python
'''

from .._impl import (
    nested_service2_SimpleNestedService2 as SimpleNestedService2,
)

