# coding=utf-8
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "package-name"
version = "0.0.0"
requires-python = ">=3.8"
description = "project description"
dependencies = [
    "requests",
    "conjure-python-client>=2.8.0,<4",
]

[tool.hatch.build.targets.wheel]
packages = ["."]
