# coding=utf-8
# This file has been generated by conjure-python version 0.0.0
# https://github.com/palantir/conjure-python

from .._impl import (
    nested_service_SimpleNestedService as SimpleNestedService,
    nested_service_SimpleObject as SimpleObject,
)

