# coding=utf-8

'''
This file has been generated by conjure-python version 0.0.0
https://github.com/palantir/conjure-python
'''

__all__ = [
    'another',
    'package_name',
    'product',
    'product_datasets',
]

__conjure_generator_version__ = "0.0.0"

__version__ = "0.0.0"

