# coding=utf-8
# This file has been generated by conjure-python version 0.0.0
# https://github.com/palantir/conjure-python

from setuptools import (
    find_packages,
    setup,
)

setup(
    name='package-name',
    version='0.0.0',
    python_requires='>=3.8',
    description='project description',
    package_data={"": ["py.typed"]},
    packages=find_packages(),
    install_requires=[
        'requests',
        'conjure-python-client>=2.1.0,<3',
    ],
)
