# coding=utf-8
# This file has been generated by conjure-python version 0.0.0
# https://github.com/palantir/conjure-python

from .._impl import (
    nested_deeply_nested_service_DeeplyNestedService as DeeplyNestedService,
)

